In [6]:
import torch
import torch.nn as nn
import numpy as np

a = torch.tensor([[1.,2,3,4,5]], requires_grad = True)
b = torch.tensor([[1.,2,1]], requires_grad = True)
c = torch.tensor([[1.,3.,-1]], requires_grad = True)
loss_fn = torch.nn.MSELoss(reduce=True, size_average=False)
loss = loss_fn(b,c)
print(loss)

tensor(5., grad_fn=<MseLossBackward0>)


/home/wanghonglang/.local/lib/python3.10/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [4]:
cov1 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=3,stride=2,padding=2,bias=False)
q = cov1(a)
f = torch.sum(q)
f.backward()


tensor(-2.0157, grad_fn=<SumBackward0>)

In [3]:
print(a.grad)
print(b.grad)


tensor([[ 0.2307, -0.2139,  0.2307, -0.2139,  0.2307]])
None


tensor([ 18.0000, -21.6000])
tensor([1.5000, 3.0000])